[[metadata.githubassets]]
repo = "kkdai/youtube"
asset = "youtubedr_2.7.0_linux_arm64.tar.gz"
destination = "bin"

[[metadata.githubasset]]
repo = "eugeneware/ffmpeg-static"
asset = "linux-x64"
destination = "bin/ffmpeg"